config:
  css:
    theme:
      css/mapbox.config.css: {}
  js:
    js/common.js: {}
    js/mapbox.preview.js: {}

widget:
  css:
    theme:
      css/mapbox.widget.css: {}
  js:
    js/common.js: {}
    js/mapbox.renderer.js: {}

renderer:
  css:
    theme:
      css/mapbox.renderer.css: {}
  js:
    js/common.js: {}
    js/mapbox.renderer.js: {}

views:
  css:
    theme:
      css/mapbox.renderer.css: {}
  js:
    js/common.js: {}
    js/mapbox.views.js: {}

apis:
  version: 2.5.0
  js:
    https://api.mapbox.com/mapbox-gl-js/v2.5.0/mapbox-gl.js: { type: external }
  css:
    theme:
      https://api.mapbox.com/mapbox-gl-js/v2.5.0/mapbox-gl.css: { type: external }
